#:schema node_modules/wrangler/config-schema.json
name = "dingyuezhuanhuan"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f56bad6f636e4ba69b5797ec550c80b4" }
]

[assets]
directory = "./public"
